name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install PyInstaller
      run: pip install pyinstaller
    - name: Build Binary with PyInstaller
      run: pyinstaller --onefile -n commitme commitme.py
    - name: Upload Linux Release Asset
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ github.event.release.tag_name }}-linux
        files: |
          ./dist/commitme
          commitme.properties.template

  build-macos:
    runs-on: macos-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install PyInstaller
      run: pip install pyinstaller
    - name: Build Binary with PyInstaller for macOS
      run: pyinstaller --onefile -n commitme commitme.py
    - name: Upload macOS Release Asset
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ github.event.release.tag_name }}-macos
        files: |
          ./dist/commitme
          commitme.properties.template