name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.2'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install PyInstaller
      run: pip install pyinstaller
    - name: Build Binary with PyInstaller
      run: pyinstaller --onefile -n commitme commitme.py
    - name: Upload Linux Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/commitme
        asset_name: linux/commitme
        asset_content_type: application/octet-stream
    - name: Upload Linux Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: commitme.properties.json.template
        asset_name: linux/commitme.properties.json.template
        asset_content_type: application/octet-stream

  build-macos:
    runs-on: macos-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.2'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install PyInstaller
      run: pip install pyinstaller
    - name: Build Binary with PyInstaller for macOS
      run: pyinstaller --onefile -n commitme commitme.py
    - name: Upload MacOS Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/commitme
        asset_name: macos/commitme
        asset_content_type: application/octet-stream
    - name: Upload MacOS Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: commitme.properties.json.template
        asset_name: macos/commitme.properties.json.template
        asset_content_type: application/octet-stream